language: go
sudo: false

services:
  - docker

go:
  - go: 1.7
  - go: 1.8

before_install:
  - go get github.com/mattn/goveralls
  
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

after_success:
  - export REPO=studiously/classsvc
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO